import type { ContentAsset, Platform } from "./types";

export const ASSET_SPECS: Record<Platform, { count: number; brief: string; minLength: number; notes: string[] }> = {
  website: { count: 1, minLength: 500, notes: ["seoTitle", "metaDescription", "slug"], brief: "One complete website article, not just an SEO summary. Write a headline, lead, 3-5 meaningful sections with H2 headings, source-backed details, a concise conclusion and CTA. Target 500-800 English/Vietnamese words or 800-1200 Chinese characters only if evidence supports it. meta: seoTitle, metaDescription, slug, keyTerms. Do not copy a source date into publication date." },
  facebook: { count: 2, minLength: 350, notes: ["visualBrief", "imageText", "firstComment"], brief: "Two independently publishable Facebook posts: A news/explainer angle, B a reader-question angle. Each content must include an engaging factual opening, context, 2-4 concrete sourced details, a cautious takeaway and a natural question or CTA. Use 4-7 readable paragraphs, optional short bullets and 0-3 relevant hashtags. Target 150-250 English/Vietnamese words or 250-450 Chinese characters when source supports it. Do not output an outline, a teaser only, or instructions such as 'explain why it matters'. Include the real destination URL if provided; otherwise omit the link. meta: visualBrief (production direction, not evidence), imageText (short factual on-image headline), firstComment (optional publishable follow-up). Do NOT put visual directions into content." },
  threads: { count: 1, minLength: 250, notes: ["replies"], brief: "One complete conversation thread. content includes a main post and 3-5 numbered replies, all fully written and ready to copy separately. Each part should stay within 500 characters. Move from opening fact to details to a genuine audience question. Also put replies in meta.replies as an array. No invented audience opinions." },
  linkedin: { count: 1, minLength: 450, notes: ["visualBrief"], brief: "One professional post with a factual opening, context, 2-3 evidence-led points, implications explicitly framed as interpretation, and a closing question/CTA. 5-7 readable paragraphs; target 200-350 English/Vietnamese words or 400-650 Chinese characters if supported. Avoid fake personal experience and generic business filler. meta.visualBrief describes an optional editorial graphic." },
  x: { count: 1, minLength: 180, notes: ["posts"], brief: "One numbered thread of 3-5 fully written posts, each <=280 characters including numbering and link (conservative raw count). Include the complete thread in content and individual posts in meta.posts. Each post adds a sourced detail; final post gives context link or question. Do not cram all facts into one overlong tweet." },
  instagram: { count: 1, minLength: 350, notes: ["slides", "caption", "visualBrief"], brief: "One 6-slide carousel. content must contain final copy for each numbered slide plus a separately labeled publishable caption and CTA. Slides: hook, context, fact 1, fact 2 or limitation, what remains uncertain, recap/CTA. Keep slide copy short; no invented advice when source has no recommendations. meta.slides: six objects with title, body, visualDirection; meta.caption, slideCount=6, visualBrief. Visuals must not imply fabricated documentary evidence." },
  short_video: { count: 2, minLength: 300, notes: ["duration", "shots", "caption"], brief: "Two complete video scripts with distinct duration: 30s and 60s. Each content includes timed segments, exact spoken narration, on-screen text and shot direction, then a posting caption. 30s: 0-3,3-10,10-22,22-30; 60s: 0-3,3-15,15-35,35-52,52-60. Budget realistic speech length in requested language. Never use 'explain this' instead of actual narration. meta.duration must be 30s or 60s; meta.shots is an array of time/narration/onScreen/visual; meta.caption. Only suggest illustrative graphics, not fake testimony or screenshots." },
  community: { count: 1, minLength: 220, notes: ["options", "pinnedReply"], brief: "One complete community post with title, factual context, an open question, 4 neutral poll choices, invitation to comment and a written moderator pinned reply. Include all publishable text in content. meta.options is four strings; meta.pinnedReply. Poll asks about information needs, not invented survey results or buy/sell recommendations." },
  push: { count: 3, minLength: 25, notes: ["pushTitle", "pushBody", "audience", "sendWindow", "frequency"], brief: "Three push variants: news-led, question-led, read-more-led. Each has an actual short title <=40 characters and body <=100 characters, localized and not sensational. content clearly labels title and body; meta.pushTitle and meta.pushBody contain exact copy. Include cta and deepLink only if real URL exists. meta.audience, sendWindow, frequency must be explicitly labeled proposed settings, not actual user analytics or scheduled sends. No automatic sending, false urgency, or placeholder URLs." },
  kol_live: { count: 1, minLength: 400, notes: ["segments", "promoCopy"], brief: "One usable 30-minute LIVE run-of-show with timed opening, source-backed explanation, 3 discussion questions with factual talking points, audience Q&A and closing CTA. Include written opening and closing, not just topic names. Unknown questions must be referred back for verification. Include a publishable promotional post in content and meta.promoCopy; meta.segments with time/topic/hostScript. Proposed running time is a production suggestion, not a source fact." },
  faq: { count: 1, minLength: 300, notes: ["questions"], brief: "One FAQ with 5-8 complete question-and-answer pairs specific to the source. Each answer must actually answer the question using available facts; if unknown, state that the source does not specify. Include all Q&A in content and meta.questions as question/answer objects. Do not repeat 'read the article' as every answer. Finish with source CTA." }
};

export function assetQualityIssues(asset: ContentAsset): string[] {
  const spec = ASSET_SPECS[asset.platform];
  const issues: string[] = [];
  if (asset.content.length < spec.minLength) issues.push("Draft may be too brief for this format; check source coverage");
  for (const key of spec.notes) {
    const value = asset.meta?.[key];
    if (value === undefined || value === null || value === "" || (Array.isArray(value) && !value.length)) issues.push(`Missing delivery field: ${key}`);
  }
  if (asset.platform === "instagram" && (!Array.isArray(asset.meta?.slides) || asset.meta.slides.length !== 6)) issues.push("Carousel requires six slides");
  if (asset.platform === "x" && Array.isArray(asset.meta?.posts) && asset.meta.posts.some(post => typeof post !== "string" || post.length > 280)) issues.push("Check X post character limits");
  if (asset.platform === "push" && (String(asset.meta?.pushTitle || "").length > 40 || String(asset.meta?.pushBody || "").length > 100)) issues.push("Push copy exceeds the starter character budget");
  return issues;
}
